[project]
name = "mkv-extract"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "watchdog>=6.0.0",
]

[dependency-groups]
dev = []
